In [2]:
from sentence_transformers import SentenceTransformer, util
import pandas as pd
from nltk.tokenize import sent_tokenize
model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')


Downloading:   0%|          | 0.00/968 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.79k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/645 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/471M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/239 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/480 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/14.8M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Untitled.ipynb clean_text.R


In [3]:
texts = pd.read_csv('../raw_data/texts.csv')
texts

party                                               text
0        fdp  NIE GAB ES MEHR ZU TUN. WAHLPROGRAMM DER FREIE...
1     gruene  Deutschland. Alles ist drin. Bundestagswahlpro...
2  koalition  MEHR FORTSCHRITT WAGEN BÜNDNIS FÜR FREIHEIT, G...
3        spd  Unser Zukunftsprogramm Das Zukunftsprogramm de...

In [ ]:
koalition = texts.text[2]
koalition = sent_tokenize(koalition)

In [245]:
range(len(koalition))

range(0, 3236)

In [254]:
data = pd.DataFrame()
for party in [0,1,3]:
    print(party)
    sentences1 = sent_tokenize(texts.text[party])
    embeddings1 = model.encode(sentences1, convert_to_tensor=True,show_progress_bar = True)

    for sent in range(len(koalition)):
        print(sent)
        embeddings2 = model.encode(koalition[sent], convert_to_tensor=True,show_progress_bar = True)

        #Compute cosine-similarits
        cosine_scores = util.pytorch_cos_sim(embeddings1, embeddings2)
        #Output the pairs with their score

        pairs = []
        for i in range(len(sentences1)):
            pairs.append({'index': [i], 
                          'score': float(cosine_scores[i][0]), 
                          'sentence': sentences1[i], 
                          'sentence_coal': sent,
                          'party': party})
            df = pd.DataFrame(pairs).nlargest(2,'score')
        data = pd.concat([df,data])

0


Batches:   0%|          | 0/142 [00:00<?, ?it/s]

0


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

1


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

3


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

4


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

5


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

6


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

7


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

8


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

9


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

10


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

11


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

12


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

13


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

14


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

15


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

16


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

17


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

18


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

19


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

20


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

21


Batches:   0%|          | 0/1 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [239]:
range(len(koalition))

range(0, 3236)

In [262]:
data.head(10)

index     score                                           sentence  \
3026  [3026]  0.599247  Nur so kön- nen wir die digitale Transformatio...   
3056  [3056]  0.513064  So schaffen wir ein Europa, das digital unabhä...   
3769  [3769]  0.504595  Aus Sicht der Freien Demokraten ist die Einbez...   
3569  [3569]  0.477271   Es ist das vornehmste Recht in einer Demokratie.   
2641  [2641]  0.471362  Ein Alleingang der EU könnte dagegen auch in D...   
2462  [2462]  0.460732  Wir wollen den Wettbewerb national und interna...   
3832  [3832]  0.557574  Die Folgen des Klima- wandels und von Überfisc...   
3746  [3746]  0.527332  Deutschland und Europa haben sich zur Klimaneu...   
4098  [4098]  0.476166  Weltweit wer- den Krisen und Konflikte in den ...   
2338  [2338]  0.393974  Wir haben uns in der Krise an die Basistechnol...   

      sentence_coal  party  
3026             20      0  
3056             20      0  
3769             19      0  
3569             19      0  
2641             18      0  
2462             18      0  
3832             17      0  
3746             17      0  
4098             16      0  
2338             16      0

In [271]:
len(sent_tokenize(texts.text[0]))

4523

In [22]:
fdp = [re.sub("((?<=[a-z])- (?=[a-z]))",'',sentence) for sentence in sent_tokenize(texts.text[0])]
spd = [re.sub("((?<=[a-z])- (?=[a-z]))",'',sentence) for sentence in sent_tokenize(texts.text[1])]
gruene = [re.sub("((?<=[a-z])- (?=[a-z]))",'',sentence) for sentence in sent_tokenize(texts.text[3])]
coal = [re.sub("((?<=[a-z])- (?=[a-z]))",'',sentence) for sentence in sent_tokenize(texts.text[2])]

In [23]:
fdp_embed = model.encode(fdp, convert_to_tensor=True,show_progress_bar = True, batch_size = 64)
spd_embed = model.encode(spd, convert_to_tensor=True,show_progress_bar = True, batch_size = 64)
gruene_embed = model.encode(gruene, convert_to_tensor=True,show_progress_bar = True, batch_size = 64)
koalition_embed = model.encode(coal, convert_to_tensor=True,show_progress_bar = True, batch_size = 64)



#Output the pairs with their score


Batches:   0%|          | 0/71 [00:00<?, ?it/s]

Batches:   0%|          | 0/58 [00:00<?, ?it/s]

Batches:   0%|          | 0/36 [00:00<?, ?it/s]

Batches:   0%|          | 0/51 [00:00<?, ?it/s]

In [233]:
print(fdp_sim)
print(gruene_sim)
print(spd_sim)

tensor([[0.8164]])
tensor([[0.8826]])
tensor([[0.4912]])


In [24]:
fdp_sim = util.pytorch_cos_sim(fdp_embed, koalition_embed)
fdp_sim = fdp_sim.numpy()
fdp_sim_pd = pd.DataFrame(fdp_sim).reset_index().rename({'index':'index_party'}, axis = 'columns')

gruene_sim = util.pytorch_cos_sim(gruene_embed, koalition_embed)
gruene_sim = gruene_sim.numpy()
gruene_sim_pd = pd.DataFrame(gruene_sim).reset_index().rename({'index':'index_party'}, axis = 'columns')

spd_sim = util.pytorch_cos_sim(spd_embed, koalition_embed)
spd_sim = spd_sim.numpy()
spd_sim_pd = pd.DataFrame(spd_sim).reset_index().rename({'index':'index_party'}, axis = 'columns')

In [25]:
fdp_data = pd.DataFrame(fdp,columns = ['sent']).reset_index().rename({'index':'index_party'}, axis = 'columns')
gruene_data = pd.DataFrame(gruene,columns = ['sent']).reset_index().rename({'index':'index_party'}, axis = 'columns')
spd_data = pd.DataFrame(spd,columns = ['sent']).reset_index().rename({'index':'index_party'}, axis = 'columns')
coal_data = pd.DataFrame(coal,columns = ['sent']).reset_index().rename({'index':'index_party'}, axis = 'columns')

In [26]:
fdp_sim_pd.to_csv('../results/matrix_fdp.csv')
gruene_sim_pd.to_csv('../results/matrix_gruene.csv')
spd_sim_pd.to_csv('../results/matrix_spd.csv')

fdp_data.to_csv('../results/data_fdp.csv')
gruene_data.to_csv('../results/data_gruene.csv')
spd_data.to_csv('../results/data_spd.csv')
coal_data.to_csv('../results/data_coal.csv')

In [19]:
import re
[re.sub("((?<=[a-z])- (?=[a-z]))",'',str(sentence)) for sentence in fdp_data.sent]

['NIE GAB ES MEHR ZU TUN.',
 'WAHLPROGRAMM DER FREIEN DEMOKRATEN Wir sind Freie Demokraten.',
 'Wir glauben, dass Deutschland jetzt einen Neustart braucht.',
 'Wir glauben, dass es moderner, digitaler und freier werden muss.',
 'Wir glauben an das große Potenzial unseres Landes.',
 'Wir sind bereit, Verantwortung dafür zu übernehmen.',
 'DAS PROGRAMM DER FREIEN DEMOKRATEN ZUR BUNDESTAGSWAHL 2021 Beschluss des 72.',
 'Ord.',
 'Bundesparteitag der Freien Demokraten vom 14.–16.',
 'Mai 2021 INHALT Wie es ist, darf es nicht bleiben \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 4 Werden wir das Land, das in uns steckt \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 \x08 

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Untitled.ipynb clean_text.R


df = pd.DataFrame(pairs)

In [151]:
df = df.sort_values(by='score', ascending=False).reset_index()

In [152]:
df.head()

level_0   index     score sentence  sentence_coal  party
0     1252  [1252]  0.412663      an.              3      0
1     1250  [1250]  0.395891    will.              3      0
2      488   [488]  0.364793     ren.              3      0
3     2180  [2180]  0.353215     men.              3      0
4     1640  [1640]  0.335015      21.              3      0

In [138]:
print(df.sentence[4])

Für die Wahlen zum Europäischen Parlament setzen wir uns dafür ein, dass die Bürger*innen mit ihrer Stimme für einen Spitzenkandidaten bzw.


In [ ]:
fdp_sim = util.pytorch_cos_sim(torch.mean(fdp_embed,axis = 0), torch.mean(koalition_embed,axis = 0))
gruene_sim = util.pytorch_cos_sim(torch.mean(spd_embed,axis = 0), torch.mean(koalition_embed,axis = 0))
spd_sim = util.pytorch_cos_sim(torch.mean(gruene_embed,axis = 0), torch.mean(koalition_embed,axis = 0))

fdp_sim_all = util.pytorch_cos_sim(fdp_embed, koalition_embed)
gruene_sim_all = util.pytorch_cos_sim(spd_embed,koalition_embed)
spd_sim_all = util.pytorch_cos_sim(gruene_embed,koalition_embed)